{application,soap,
             [{applications,[kernel,stdlib,elixir,logger,sweet_xml,httpoison,
                             xml_builder]},
              {description,"SOAP client for Elixir programming language\n"},
              {modules,['Elixir.OperationError','Elixir.Soap',
                        'Elixir.Soap.Request','Elixir.Soap.Request.Headers',
                        'Elixir.Soap.Request.Params','Elixir.Soap.Response',
                        'Elixir.Soap.Response.Parser','Elixir.Soap.Type',
                        'Elixir.Soap.Wsdl','Elixir.Soap.Xsd']},
              {registered,[]},
              {vsn,"1.0.1"}]}.
